<Project Sdk="Aspire.AppHost.Sdk/13.4.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>8564a104-292c-4b18-a842-08411de7a193</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AspireApp.ApiService\AspireApp.ApiService.csproj" />
    <ProjectReference Include="..\AspireApp.Web\AspireApp.Web.csproj" />
  </ItemGroup>

</Project>
